name: Testing Out Github Actions
run-name: I am ${{ github.actor }}
on: [push]
jobs:
  Let's see:
  runs-on: ubuntu-latest
  steps:
    - name: Echo Something
      run: echo "something"
      run: echo ${{ job.status }}
  
